# Generated by Django 5.2.5 on 2025-08-26 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source_name', models.CharField(max_length=50, unique=True, verbose_name='Data Source')),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'db_table': 'apiapp_data_source',
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('object_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_type_name', models.CharField(max_length=50, unique=True, verbose_name='Object Type')),
            ],
            options={
                'verbose_name': 'Object Type',
                'verbose_name_plural': 'Object Types',
                'db_table': 'apiapp_object_type',
                'ordering': ['object_type_name'],
            },
        ),
        migrations.CreateModel(
            name='UnitCategory',
            fields=[
                ('unit_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_category_name', models.CharField(max_length=100, verbose_name='Unit Category Name')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unit Category',
                'verbose_name_plural': 'Unit Categories',
                'db_table': 'apiapp_unit_category',
                'ordering': ['unit_category_name'],
            },
        ),
        migrations.CreateModel(
            name='UnitDefinition',
            fields=[
                ('unit_definition_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_definition_name', models.CharField(max_length=100, verbose_name='Unit Definition Name')),
                ('scale_factor', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Scale Factor')),
                ('offset', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Offset')),
                ('is_base', models.BooleanField(default=False, verbose_name='Is Base Unit')),
                ('alias_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alias Text')),
                ('precision', models.IntegerField(verbose_name='Precision')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('calculation_method', models.IntegerField(blank=True, null=True, verbose_name='Calculation Method')),
            ],
            options={
                'verbose_name': 'Unit Definition',
                'verbose_name_plural': 'Unit Definitions',
                'db_table': 'apiapp_unit_definition',
                'ordering': ['unit_definition_name'],
            },
        ),
        migrations.CreateModel(
            name='UnitSystem',
            fields=[
                ('unit_system_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_system_name', models.CharField(max_length=100, unique=True, verbose_name='Unit System Name')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unit System',
                'verbose_name_plural': 'Unit Systems',
                'db_table': 'apiapp_unit_system',
                'ordering': ['unit_system_name'],
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('unit_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_type_name', models.CharField(max_length=100, unique=True, verbose_name='Unit Type Name')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unit Type',
                'verbose_name_plural': 'Unit Types',
                'db_table': 'apiapp_unit_type',
                'ordering': ['unit_type_name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectInstance',
            fields=[
                ('object_instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_instance_name', models.CharField(max_length=50, unique=True, verbose_name='Object Instance')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.objecttype', verbose_name='Object Type')),
            ],
            options={
                'verbose_name': 'Object Instance',
                'verbose_name_plural': 'Object Instances',
                'db_table': 'apiapp_object_instance',
                'ordering': ['object_instance_name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectTypeProperty',
            fields=[
                ('object_type_property_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_type_property_name', models.CharField(max_length=50, verbose_name='Object Type Property')),
                ('object_type_property_category', models.CharField(max_length=50, verbose_name='Category')),
                ('tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag')),
                ('openserver', models.CharField(blank=True, max_length=100, null=True, verbose_name='OpenServer')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.objecttype', verbose_name='Object Type')),
                ('unit_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.unitcategory', verbose_name='Unit Category')),
                ('unit', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.unitdefinition', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Object Type Property',
                'verbose_name_plural': 'Object Type Properties',
                'db_table': 'apiapp_object_type_property',
                'ordering': ['object_type_property_name'],
                'unique_together': {('object_type', 'object_type_property_name')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='models_files/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiapp.datasource', verbose_name='Data Source')),
            ],
            options={
                'verbose_name': 'Scenario Component',
                'verbose_name_plural': 'Scenario Components',
                'db_table': 'apiapp_scenario_component',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ServersClass',
            fields=[
                ('server_id', models.AutoField(primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=50, unique=True)),
                ('server_url', models.CharField(max_length=250, unique=True)),
                ('server_status', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'db_table': 'apiapp_servers',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioClass',
            fields=[
                ('scenario_id', models.AutoField(primary_key=True, serialize=False)),
                ('scenario_name', models.CharField(max_length=50, unique=True, verbose_name='Scenario')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.serversclass', verbose_name='Server')),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
                'db_table': 'apiapp_scenarios',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='unitdefinition',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiapp.unittype', verbose_name='Unit Type'),
        ),
        migrations.AddField(
            model_name='unitcategory',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiapp.unittype', verbose_name='Unit Type'),
        ),
        migrations.CreateModel(
            name='MainClass',
            fields=[
                ('data_set_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_source_id', models.IntegerField()),
                ('value', models.DecimalField(db_column='value', decimal_places=28, max_digits=38, null=True)),
                ('date_time', models.DateTimeField(db_column='date', null=True, verbose_name='Date')),
                ('sub_data_source', models.CharField(max_length=50, null=True, verbose_name='Category')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('data_source_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiapp.datasource', verbose_name='Data Source')),
                ('object_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.objectinstance', verbose_name='Object Instance')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.objecttype', verbose_name='Object Type')),
                ('object_type_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.objecttypeproperty', verbose_name='Object Type Property')),
            ],
            options={
                'verbose_name': 'Main Data Record',
                'verbose_name_plural': 'Main Data Records',
                'db_table': 'apiapp_mainclass',
                'ordering': ['-data_source_id', 'data_source_name'],
                'indexes': [models.Index(fields=['data_source_name', 'data_source_id'], name='apiapp_main_data_so_50ec0d_idx'), models.Index(fields=['object_type', 'object_type_property'], name='apiapp_main_object__47245b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScenarioComponentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.scenariocomponent', verbose_name='Component')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.scenarioclass', verbose_name='Scenario')),
            ],
            options={
                'verbose_name': 'Scenario Component Link',
                'verbose_name_plural': 'Scenario Component Links',
                'db_table': 'apiapp_scenario_component_link',
                'unique_together': {('scenario', 'component')},
            },
        ),
        migrations.CreateModel(
            name='UnitSystemCategoryDefinition',
            fields=[
                ('unit_system_category_definition_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('unit_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.unitcategory', verbose_name='Unit Category')),
                ('unit_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.unitdefinition', verbose_name='Unit Definition')),
                ('unit_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.unitsystem', verbose_name='Unit System')),
            ],
            options={
                'verbose_name': 'Unit System Category Definition',
                'verbose_name_plural': 'Unit System Category Definitions',
                'db_table': 'apiapp_unit_system_category_definition',
                'ordering': ['unit_system', 'unit_category'],
                'unique_together': {('unit_system', 'unit_category', 'unit_definition')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='unitdefinition',
            unique_together={('unit_definition_name', 'unit_type')},
        ),
        migrations.AlterUniqueTogether(
            name='unitcategory',
            unique_together={('unit_category_name', 'unit_type')},
        ),
    ]
