# Generated by Django 5.2.5 on 2025-09-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_scenariolog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenariolog',
            options={'verbose_name': 'ScenarioLog', 'verbose_name_plural': 'ScenarioLogs'},
        ),
        migrations.AddField(
            model_name='scenarioclass',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='scenariolog',
            table='apiapp_scenariolog',
        ),
    ]
